name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Bundler CLI
      uses: CultureHQ/actions-bundler@v1.0.0
    
    - name: Install dependencies
      run: make loadLibs
      
    - name: Run check
      run: make all
